### ISSUE TITLE
[QEMU] By activating the --enable-kvm parameter, the bootloader is no longer initialized.

### ISSUE THREAD

**Issue by ionutnechita** [slimbootloader/slimbootloader#1055]
Hi Slimbootloader Team,

At the moment, starting with Qemu works, but I would also like to started with virtual acceleration using the KVM driver.
I tried several options in Qemu, but I couldn't started it with KVM acceleration.

qemu-system-x86_64 -machine q35 -m 1024 --nographic -boot order=d -pflash SlimBootloader.bin --enable-kvm -cpu host                  WARNING: Image format was not specified for 'SlimBootloader.bin' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
At this moment it remains so, without anything appearing on the console.

Can you help me with this issue?
Thanks for the support you provide so far.

**Comment by mauricema** [comment]
Provided a fix for the KVM boot issue.  Please try it out.
https://github.com/slimbootloader/slimbootloader/pull/1056

Regards
-Maurice
