### ISSUE TITLE
Attempting to access Elkhart Lake Memory Settings Through ConfigEditor crashes

### ISSUE THREAD

**Issue by aaronpop** [slimbootloader/slimbootloader#1122]
Using the latest github, running ConfigEditor.py and attempting to access ElkhartlakeBoardPkg's CfgDataDef.yaml's "Memory Settings"->"MEM Training" causes the utility to crash.

Python 3.6.6 on Windows 10 X64

**Comment by mauricema** [comment]
Please check this PR:  https://github.com/slimbootloader/slimbootloader/pull/1123
It will fix this issue.

**Comment by aaronpop** [comment]
Closing issue. Duplicate of #1123
