### ISSUE TITLE
Dockerfile installs incompatible git version

### ISSUE THREAD

**Issue by fitzged** [slimbootloader/slimbootloader#1136]
With the change added to verify correct tool versions are being used (bc5584d176878a154bb79cd8a94487dceb215670), the Dockerfile needs updating to pull the latest git version for Ubuntu 18.04 from the ppa:git-core/ppa repo, otherwise builds fail:
Checking Toolchain Versions...
- /usr/bin/python: Version 3.6.9 (>= 3.6.0) [PASS]
- /usr/bin/openssl: Version 1.1.1 (>= 1.1.0g) [PASS]
- /usr/bin/nasm: Version 2.13.02 (>= 2.12.02) [PASS]
- /usr/bin/iasl: Version 20160831 (>= 20160422) [PASS]
- /usr/bin/git: Version 2.17.1 (>= 2.20.0) [FAIL]
- /usr/bin/gcc: Version 7.5.0 (>= 7.3) [PASS]
...Failed! Please check toolchain versions!

**Comment by myguitar** [comment]
Thanks for reporting 'git' version check issue. #1137 will print recommended 'git' version if not met and continue to build.

**Comment by fitzged** [comment]
Great, thanks @myguitar that will work for me.

**Comment by myguitar** [comment]
No problem. Let me close this.
