### ISSUE TITLE
[Question] Is possible to preserve boot entry at reboot slimbootloader?

### ISSUE THREAD

**Issue by ionutnechita** [slimbootloader/slimbootloader#1144]
Hi Slimbootloader Team,

I made a change to the boot input menu.
But from what I see it is not preserved at reboot.
Is there any possibility that it will be kept?

Maybe through the CMOS area.

Shell> boot
Boot options (in HEX):

Idx|ImgType|DevType|DevNum|Flags|HwPart|FsType|SwPart|File/Lbaoffset
  0|      0|   MMC |    0 |   0 |    0 |  FAT |    0 | iasimage.bin
  1|      0|   MMC |    0 |   0 |    0 |  RAW |    1 | 0x0
  2|      0|  SATA |    0 |   0 |    0 |  FAT |    0 | iasimage.bin
  3|      0|   USB |    0 |   0 |    0 |  FAT |    0 | iasimage.bin
  4|      4|   MEM |    0 |   0 |    0 |  RAW |    0 | 0x0

-->

Idx|ImgType|DevType|DevNum|Flags|HwPart|FsType|SwPart|File/Lbaoffset
  0|      4|   MEM |    0 |   0 |    0 |  RAW |    0 | 0x0
  1|      0|   MMC |    0 |   0 |    0 |  RAW |    1 | 0x0
  2|      0|  SATA |    0 |   0 |    0 |  FAT |    0 | iasimage.bin
  3|      0|   USB |    0 |   0 |    0 |  FAT |    0 | iasimage.bin
  4|      0|   MMC |    0 |   0 |    0 |  FAT |    0 | iasimage.bin

Thanks.

**Comment by rprangar** [comment]
Hi

The boot options are part of configuration data and is signed/verified by Slim Bootloader. So, as such, any changes to this would have to be re-signed and re-built/stitched. You can refer this page for details - https://slimbootloader.github.io/how-tos/change-boot-option.html

To achieve what you are asking, the boot order can be updated by platform code and this can be done during every boot to make it effective every boot. One **example** implementation using CMOS is here - https://github.com/slimbootloader/slimbootloader/blob/8400e628b569b8dbe0fc88db2ff305aa696e6084/Platform/QemuBoardPkg/Library/Stage2BoardInitLib/Stage2BoardInitLib.c#L359. Please consider security implications to adopt this approach. 

Thanks
Ravi
