### ISSUE TITLE
getboardid for tigerlake

### ISSUE THREAD

**Issue by erik-kline** [slimbootloader/slimbootloader#1167]
in
 https://github.com/slimbootloader/slimbootloader/blob/master/Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c

GetBoardId is called and later the board id is set via  SetPlatformId (BoardId);

in GetBoardId in the file below
https://github.com/slimbootloader/slimbootloader/blob/master/Platform/TigerlakeBoardPkg/Library/Stage1BBoardInitLib/EcSupport.c

This function reads the board address from communication over the pci bus. This  will always overwrite whatever the previous board id was. In the event of a error it will overwrite it with 0xff. 

*BoardId = 0xFF

**Comment by mauricema** [comment]
The following commit should fix this issue.
https://github.com/slimbootloader/slimbootloader/commit/383a5b4e23ad132942527661cdba8959cc22cc78
Since it was merged,  I will close it for now.   Please reopen if it does not address your original BoardId issue.
