### ISSUE TITLE
[TGL] Hardcoded GPIO pin was used for payload ID selection

### ISSUE THREAD

**Issue by mauricema** [slimbootloader/slimbootloader#1195]
Current SBL TGL platform used hard coded GPIO pin for payload ID selection.  
The preferred way is to use CFGDATA to allow platform determine which GPIO pin to use for payload ID section.  
Please look into CFL implementation for reference.

**Comment by LeanSheng** [comment]
#1204 This is the PR for fix. Please take a look.
