### ISSUE TITLE
[EHL] Hardcoded GPIO pin was used for payload ID selection

### ISSUE THREAD

**Issue by mauricema** [slimbootloader/slimbootloader#1196]
Current SBL EHL platform used hard coded GPIO pin for payload ID selection.  
The preferred way is to use CFGDATA to allow platform determine which GPIO pin to use for payload ID section.  
Please look into CFL implementation for reference.

**Comment by koktong-ong** [comment]
In SBL EHL Stage2BoardInitLib.c function UpdatePayloadId(VOID) :
```
  GenCfgData = (GEN_CFG_DATA *)FindConfigDataByTag (CDATA_GEN_TAG);
  if (GenCfgData == NULL) {
    ASSERT (FALSE);
    return;
  }
  SetPayloadId (GenCfgData->PayloadId);

  if (GetPayloadId () != AUTO_PAYLOAD_ID_SIGNATURE) {
    return;
  }
```
Payload ID will only check GPIO setting if 'AUTO' was detected in CFGDATA 
Else the Payload ID will get from CFGDATA

**Comment by LeanSheng** [comment]
> In SBL EHL Stage2BoardInitLib.c function UpdatePayloadId(VOID) :
> 
> ```
>   GenCfgData = (GEN_CFG_DATA *)FindConfigDataByTag (CDATA_GEN_TAG);
>   if (GenCfgData == NULL) {
>     ASSERT (FALSE);
>     return;
>   }
>   SetPayloadId (GenCfgData->PayloadId);
> 
>   if (GetPayloadId () != AUTO_PAYLOAD_ID_SIGNATURE) {
>     return;
>   }
> ```
> 
> Payload ID will only check GPIO setting if 'AUTO' was detected in CFGDATA
> Else the Payload ID will get from CFGDATA

I thnak Maurice is referring to this line:
PayloadSelGpioPad = GPIO_VER3_GPP_D13;

We just need to let user configure via SiliconCfgData like CFL.

**Comment by mauricema** [comment]
Yes,  hardcoded pin GPIO_VER3_GPP_D13 needs to be configurable.

**Comment by koktong-ong** [comment]
Thanks @LeanSheng for helping on this!

**Comment by LeanSheng** [comment]
#1204 here is the fix
