### ISSUE TITLE
[TGL] CPU base speed error

### ISSUE THREAD

**Issue by PennZheng** [slimbootloader/slimbootloader#1233]
Hi,

I encounter an issue that the CPU base speed shown in Windows 10 Task Manager is not mathed with the CPU nominal frequency.

CPU base speed shown in Windows 10 Task Manager with **Slim Bootloader and UEFI Payload firmware** :
![Performance_CPU_SBL](https://user-images.githubusercontent.com/11797686/126954295-19c70929-e686-4ab1-9b90-c71a4ee89396.PNG)

CPU base speed shown in Windows 10 Task Manager with **AMI BIOS** on the same TGL UP3 board :
![Performance_CPU_AMI_BIOS](https://user-images.githubusercontent.com/11797686/126954278-1c1de6bf-e8a8-4f82-b4e1-2423b84dc18d.PNG)

It seems there is an error on ACPI object **_PSS (Performance Supported States)**.

The following is the Slim Bootloader and UEFI Payload source code version :

Slim Bootloader Project

> Git Repository: https://github.com/slimbootloader/slimbootloader.git
> Download Date: 2021/07/16
> Git Commit ID: ec20bf3

EDK II Project (UEFI Payload)

> Git Repository: https://github.com/tianocore/edk2.git
> Download Date: 2021/07/09
> Git Commit ID: b560e9d9b67450d3baea56d0e211066722643c57

Thanks

**Comment by japelner-intc** [comment]
Hi,

Thanks for reporting this. We will take a look at it.

Thanks,
Jim

**Comment by stanleyintel** [comment]
Hi, 

  May you check if this patch fixes the issue? 
https://github.com/slimbootloader/slimbootloader/pull/1236

**Comment by PennZheng** [comment]
Hi,

I have verify the patch on our Tiger Lake board. It does fix the CPU base speed error issue.
How does the CPOC duplication cause this issue?

Thanks

**Comment by stanleyintel** [comment]
CP0C table is for _CPC. Duplicated tables may result in wrongly access.
