### ISSUE TITLE
[TGL] Virtualization is disabled in Windows 10

### ISSUE THREAD

**Issue by PennZheng** [slimbootloader/slimbootloader#1244]
Hi,

I encounter an issue on an EC-less Tiger Lake UP3 board that virtualization is disabled in Windows 10.
![Task Manager](https://user-images.githubusercontent.com/11797686/128009972-fcec7b55-03cb-4d60-8648-31cc360cce0e.PNG)
![SYSTEMINFO](https://user-images.githubusercontent.com/11797686/128009976-774e3522-ce88-4434-985c-ad540d6f0695.PNG)

I have confirmed that the FSP UPD setting **VtdDisable** is configured as 0 (Intel VT-d is enabled).

**There is no such issue on the same board with third-party UEFI BIOS.**

The following is the Slim Bootloader and UEFI Payload source code version :

Slim Bootloader Project

- Git Repository: https://github.com/slimbootloader/slimbootloader.git
- Download Date: 2021/07/16
- Git Commit ID: ec20bf3

EDK II Project (UEFI Payload)

- Git Repository: https://github.com/tianocore/edk2.git
- Download Date: 2021/07/09
- Git Commit ID: b560e9d9b67450d3baea56d0e211066722643c57

Thanks

**Comment by PennZheng** [comment]
After setting the VtdDisable as 0 and setting the VmxEnable as 1, the virtualization is enabled in Windows 10.
What is the difference between the **VtdDisable** and **VmxEnable**?

**Comment by gdong1** [comment]
The CPU flag for Intel HW Virtualization is VMX is the CPU flag to enable Intel HW virtualization (VT-x). It is required by  hypervisor. VT-d allows hypervisor direct passthrough of devices. Often it is nice to have for hypervisor to enable virtualization.

**Comment by PennZheng** [comment]
Thanks for your reply.
