### ISSUE TITLE
[TGL] VS2019 Toolchain Build causes a CATERR side effect

### ISSUE THREAD

**Issue by Josh0041** [slimbootloader/slimbootloader#1276]
Good day. I have been working on a TGL-UP3 RVP for the past few weeks and I am bothered on the CATERR that I am getting. I have tried several times the prebuilt SBL IFWI's and it had no problems booting till the SBL Shell... so it is not a problem on the SKU. 

However whenever I build and stitch my own SBL IFWI from the mentioned packages, I consistently get a CATERR right after entry to STAGE1B. The Post Code 0x007F suggests that I have already entered pre-memory initialization. Then after a few seconds... the "happy" CATERR suddenly lights up!

I have been scratching my head for three weeks now until I decided to use my backup Windows Build Environment and wolah! The SBL IFWI generated there did not cause the CATERR and booted all the way to SBL Shell!

I've compared my Primary and Backup Build environments and I concluded that the cause of the issue is a side effect of using Visual Studio 2019 (VS2019). Aside from NASM... this is the only major tool that differs in both environments. I only experienced this when I started building TGL... did not observe this in any other platforms that I've built before.

**Primary Windows Build Environment (CATERR side-effect)**

- VS2019 Tool Chain
- OpenSSL 1.1.1k  25 Mar 2021
- Python 2.7.13
- Python 3.7.3
- ASL+ Optimizing Compiler version 20160422-32
- NASM version 2.13.03 compiled on Feb  7 2018

![image](https://user-images.githubusercontent.com/51906344/130908462-7c222aec-69f3-4f4e-b6c2-b49cfaf848b8.png)

**Secondary Windows Build Environment (Boot is successful)**

- VS2015x86 Tool Chain
- OpenSSL 1.1.1k  25 Mar 2021
- Python 2.7.16
- Python 3.7.3
- ASL+ Optimizing Compiler version 20160422-32
- NASM version 2.15.05 compiled on Aug 28 2020

![image](https://user-images.githubusercontent.com/51906344/130908591-f536e246-9e7c-4f63-9b34-fbe217d95eb9.png)

Kindly triage if this is also happening elsewhere. I will have to force the build environment to use VS2015x86 instead to circumvent this problem.

With best regards,
Josh

**Comment by rprangar** [comment]
Hi

We have been using VS 2015. We will try to see if we can reproduce the issue with VS 2019.

Thanks
Ravi

**Comment by randylintw** [comment]
Tried with SblOpen recently source and can't reproduce this issue on VS2019.

**Comment by Josh0041** [comment]
Triaged by internal team and used the provided SBL IFWI. Board is booting on internally built SBL IFWI. Closing issue for now.
