### ISSUE TITLE
Disabling signature check for development

### ISSUE THREAD

**Issue by mehmetakbulut** [slimbootloader/slimbootloader#1303]
I have unsigned IAS images coming from a trusted source during development testing in a QEMU VM. Is it possible to disable the signature check?

By changing RSA and SHA algos in `BuildLoader.py`, I'm able to make SBL boot signed IAS images but it would be better if I can build SBL with the signature checks disabled.

**Comment by mauricema** [comment]
There is a config option available and you can use it to disable verified boot.
In file Platform\QemuBoardPkg\BoardConfig.py:
Change:
self.HAVE_VERIFIED_BOOT       = 1
To:
self.HAVE_VERIFIED_BOOT       = 0

It is the intention to verify signature by default in SBL QEMU.

**Comment by mehmetakbulut** [comment]
Thank you @mauricema !
