### ISSUE TITLE
Update documentation on booting Ubuntu

### ISSUE THREAD

**Issue by evanblough** [slimbootloader/slimbootloader#1340]
I am following the guide to boot ubuntu from USB media. I am unable to do so on my TGLUP3 Rev 03 RVP board. I believe I may be missing some configuration that will allow me to boot. 

[Docs Link](https://slimbootloader.github.io/how-tos/boot-ubuntu.html)

In section 3, I am assuming you are using Ubuntu Desktop, it might help to supply a hyperlink to which image was specifically loaded.

In section 4, it says to flash a USB stick with the Rufus tool. I have used the defaults and they haven't worked. If there is non-default configuration for flashing ubuntu to the USB drive, that should be called out somewhere in the document.

In section 5, it says to run the following command to swap your boot order. This seems to be device specific because the TGL platform seems to only have 3 selectable boot options in it's default configuration. It would be helpful to the documentation to include what configuration needs to be used for the CfgData_BootOption.yaml file. 

Here is my serial output when formatting my flash drive with dd.

======== Try Booting with Boot Option 0 ========
BootMediumPciBase(0x1400)
Getting boot image from USB
Init USB XHCI - Success
Enumerate Bus - Success
Found 1 USB devices on bus
Use the 1st mass storage device
Found 1 mass storage devices
Try to find boot partition
Protective MBR does not protect the whole drive!
Primary GPT Header CalculateCrc32 Error!
Secondary GPT Header CalculateCrc32 Error!
Partition type: UNKNOWN  (1 logical partitions)
Find partition success
Init File system
No partitions found, Status = Invalid Parameter
Failed to Initialize Boot File System - SwPart 1
Payload normal heap: 0xF000000 (0x50000 used)
Payload reserved heap: 0xF00000 (0x0 used)
Payload stack: 0xF0000 (0x978 used)

Here is my serial output when formatting my drive with Rufus and ISO format.

Idx|ImgType|DevType|DevNum|Flags|HwPart|FsType|SwPart|File/Lbaoffset
  0|      0|   USB |    0 |  10 |    0 |  FAT |    1 | /boot/sbl_os *Current
  1|      0|  NVME |    0 |  10 |    0 | EXT2 |    1 | /boot/sbl_os
  2|      0|  SATA |    0 |  10 |    0 | EXT2 |    1 | /boot/sbl_os

======== Try Booting with Boot Option 0 ========
BootMediumPciBase(0x1400)
Getting boot image from USB
Init USB XHCI - Success
Enumerate Bus - Success
Found 1 USB devices on bus
Use the 1st mass storage device
Found 1 mass storage devices
Try to find boot partition
Partition type: MBR  (1 logical partitions)
Find partition success
Init File system
No partitions found, Status = Invalid Parameter
Failed to Initialize Boot File System - SwPart 1
Payload normal heap: 0xF000000 (0x50000 used)
Payload reserved heap: 0xF00000 (0x0 used)
Payload stack: 0xF0000 (0x938 used)

Both of those outputs use the same CfgData_BootOption.yaml configuration

**Comment by evanblough** [comment]
I was using this as a stepping stone to boot Cent OS 8.4 from USB. I was able to do this successfully using the comments you provided. I am not funded to investigate whether or not Ubuntu 18.04 boots, but I am guessing it most likely will. It may help others in the future to attach the platform Cfg_BootOptions.yaml to the readme. Thank you for the assistance.

**Comment by mauricema** [comment]
Np.   Thank you for the updates.  Glad to know your original issue was addressed.
