### ISSUE TITLE
A file encode issue in the ApollolakePkg Heci Libray header file.

### ISSUE THREAD

**Issue by Eathonhsu** [slimbootloader/slimbootloader#14]
Dear Slim boot loader team,

There is a compile issue when use Visual studio 2015, I tried to bring up an Apollo lake platform.

- Silicon\ApollolakePkg\Include\Library/HeciLib.h: warning **C4819**: The file contains a character that cannot be represented in the current code page (950). Save the file in Unicode format to prevent data loss

I found the root-cause in the _HeciLib.h_. (the change patch is in the attachment)

[HeciLib_Patch.zip](https://github.com/slimbootloader/slimbootloader/files/2452874/HeciLib_Patch.zip)

Sincerely,
Ethan Hsu

**Comment by mauricema** [comment]
Hi, Ethan, 

Thank you for reporting this issue and providing a patch.  
Our current process uses pull request to submit code changes. 
Are you willing to submit a pull request so that it can be merged directly ?  

Thanks
Maurice

**Comment by Eathonhsu** [comment]
Dear Maurice,

OK, I will submit a pull request soon.

Sincerely,
Ethan

**Comment by mauricema** [comment]
Thank you,  Ethan!   :)

**Comment by huang-jin-intel** [comment]
Fixed in #16.
