### ISSUE TITLE
Hardcoded Boot Medium PCI Address

### ISSUE THREAD

**Issue by mehmetakbulut** [slimbootloader/slimbootloader#1405]
`Platform/QemuBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c` hardcodes PCI addresses for boot mediums as below.
```
CONST PLT_DEVICE  mPlatformDevices[]= {
  {{0x00001F02}, OsBootDeviceSata  , 0 },
  {{0x00000300}, OsBootDeviceSd    , 0 },
  {{0x00000300}, OsBootDeviceNvme  , 0 },
  {{0x00000400}, OsBootDeviceUsb   , 0 },
  {{0x00000100}, OsBootDeviceGraphics, 0 },
  {{0x01000000}, OsBootDeviceMemory, 0 }
};
```

In my use case, I have _tons_ of pcie-root devices consuming lower PCI addresses so boot mediums are on higher addresses.

A few questions:
1. If I have a device at a different address (let's say NVMe), should I edit this source or is there a more appropriate place to make this change?
2. Is there a reason why these addresses are hardcoded as such? (i.e. is it _safe_ to change? :) )

**Comment by mauricema** [comment]
Depending on QEMU command line, the device info might change.  
This table is just a template and it can be updated at runtime using SetDeviceAddr().  You can also add/remove entries as needed.  The initial table matches the QEMU command line we provided on wiki.
