### ISSUE TITLE
disable multimedia controler

### ISSUE THREAD

**Issue by erik-kline** [slimbootloader/slimbootloader#1503]
In slimboot on a kontron tiger lake board. lspci shows
00:05.0 Multimedia controller: Intel Corporation Device 9a19 (rev 01)

This device does not show up in uefi

What is this multimedia controller. And how do I disable it. If I disable graphics. In the configuration file the video disappears from lspci 
- InternalGfx  :
        name         : Internal Graphics
        type         : Combo
        option       : $EN_DIS
        help         : >
                       Enable/disable internal graphics.
        length       : 0x01
        value        : 0x01

**Comment by mauricema** [comment]
This is Image Processing Unit (IPU).  And it has different from the internal GFX.
I don't believe TGL FSP provides option to disable IPU, so currently SBL has no way to disable it.

**Comment by erik-kline** [comment]
ok. it something that is not needed but it taking up space.

**Comment by mauricema** [comment]
Can we close this ?

**Comment by erik-kline** [comment]
yes we can close this. sorry about the delay

**Comment by mauricema** [comment]
Thanks,  no problem!
