### ISSUE TITLE
Question: Is there are pans for supporting ARM architecture and microcontrolers?

### ISSUE THREAD

**Issue by Aukstkalnis** [slimbootloader/slimbootloader#170]
Hi,

I am interested in bootloader for ARM Cortex-M architecture. Are there plans to support it?

**Comment by rprangar** [comment]
Hi

Currently, we do not have any plans to support ARM architecture. Theoretically, we believe it should be possible to support ARM architecture.

Also, we have a mailing list - https://lists.01.org/mailman/listinfo/sbl-devel to discuss such questions. 

Regards
Ravi
