### ISSUE TITLE
Do you have a porting guide for new boards?

### ISSUE THREAD

**Issue by lutooog** [slimbootloader/slimbootloader#1702]
Hi,
   I'm porting SBL on my board based on Elkhart Lake. But I have no idea to start to port it. May I ask, do you have a  step-by-step porting guide for new board?
  Thank you very much!

**Comment by randylintw** [comment]
Hi, 
There is a document called "Apollo Lake Platform Porting Guide" and could be your reference. 
Your can get it from your Intel counterpart.
