### ISSUE TITLE
ElkhartLake EcRegion area capsule update

### ISSUE THREAD

**Issue by GabrieleGiannini-Seco** [slimbootloader/slimbootloader#1711]
We are working on a custom project with SBL MR3 for Elkhart Lake
We are using the EcRegion->InputFile are to store the firmware for our embedded controller but as we can se there is no container associated to this region that can be used to create a capsule to update this area.
We suppose that we have to add the support by ourselves but are there any specific guide or documentation on this topic? On how to expand capsule update support to other flash areas?

Best Regards
Gabriele

**Comment by randylintw** [comment]
Hi, maybe you can refer the implementation of PSE FW, store in the container.
https://github.com/slimbootloader/slimbootloader/blob/ad6da2876a81d2954d7f2d410a523b240d165a0b/Platform/ElkhartlakeBoardPkg/BoardConfig.py#L294

FWupdate doc:  https://slimbootloader.github.io/security/firmware-update.html?highlight=ipfw

**Comment by randylintw** [comment]
Hi Gabriele
  I saw there is an IPS for this case, please get support through it, thanks.

**Comment by randylintw** [comment]
Hi @GabrieleGiannini-Seco, 
  I saw the IPS have been closed, can you close this, too?
