### ISSUE TITLE
USB descriptor iteration error

### ISSUE THREAD

**Issue by maldf** [slimbootloader/slimbootloader#1713]
While iterating over a USB descriptor in GetExpectedDescriptor(), the "Len" variable always uses the 1st byte in the buffer, see
https://github.com/slimbootloader/slimbootloader/blob/107fabbebdbc8ebb60dfd038c0896a99cffd1a58/BootloaderCommonPkg/Library/UsbBusLib/UsbPeim.c#L913
This is only true for the 1st iteration, thereafter the variable should advance as the descriptor advances, it should be:
Len = Buffer[parsed]

**Comment by randylintw** [comment]
Hi, 
Would you like to submit a patch to fix this issue?

**Comment by maldf** [comment]
Patch attached.
[0001-USB-fix-descriptor-parsing.txt](https://github.com/slimbootloader/slimbootloader/files/9764244/0001-USB-fix-descriptor-parsing.txt)

**Comment by randylintw** [comment]
Could you create a pull request for this fix?
