### ISSUE TITLE
Can I run slimbootloader on top of a 3rd gen xeon server?

### ISSUE THREAD

**Issue by hanxinwu1** [slimbootloader/slimbootloader#1765]
My server cpu is Ice lake_sp, can I run slimbootloader on it?

**Comment by rprangar** [comment]
Hi

We currently don't have a reference implementation of Slim Bootloader for Icelake SP platform available today. 

So, while in theory it is possible, there will be development effort to get it working on Icelake SP platform.

Thanks
Ravi
