### ISSUE TITLE
Included Lzma SDK 19 has a dangling pointer problem

### ISSUE THREAD

**Issue by galaxy4public** [slimbootloader/slimbootloader#1780]
The included Lzma SDK version 19 has a dangling pointer problem and does not compile with GCC 12.  Updating SDK to the latest version (which is 22 at the moment) and adding "CpuArch.o " to the list of objects in the Makefile in LzmaCompress solves the issue.

**Comment by rprangar** [comment]
Thanks for reporting the issue. We will take a look.

**Comment by tsaikevin** [comment]
@galaxy4public, there is a code change in tianocore may fix the similar issue. Refer to link below

https://github.com/tianocore/edk2/commit/85021f8cf22d1bd4114803c6c610dea5ef0059f1

would you try and find out if it helps? thanks

**Comment by galaxy4public** [comment]
It does address the issue. However, isn't it easier just to synchronise with the upstream? The SDK version went up from 19 to 22 and has several bugs fixed and some enhancements introduced. For my build, I just updated the Lzma SDK and then commented here, so other people would be aware.

**Comment by rprangar** [comment]
Yes, we will rebase.
