### ISSUE TITLE
[EHL]After enabling PSE_FW, SBL can't boot linux OS

### ISSUE THREAD

**Issue by lutooog** [slimbootloader/slimbootloader#1800]
Hi
    point to issue #1768
    I try to run the newest SBL with enabling PSE_FW, but it can't boot linux OS.  As a reference, when disablig PSE_FW, it can see dmesg of linux.
   Here is the log of SBL with Debug FSP. Do you have some idea?
   
[log_202301051948.txt](https://github.com/slimbootloader/slimbootloader/files/10357616/log_202301051948.txt)

**Comment by lutooog** [comment]
Log uart use this port.
<img width="726" alt="uart_port" src="https://user-images.githubusercontent.com/114660678/210955348-42140f98-cd52-480c-ba38-a9280d32a6a1.png">

**Comment by stanleyintel** [comment]
Hi,

I am not sure if my understanding is correct: 
1. Linux can output log to serial port when PSE_FW is not enabled
2. Linux cannot output log to serial port when PSE_FW is enabled

Does your board have working I/O devices? (e.g., output via a display, and input via kb/mouse; or remote connectable via SSH?)

**Comment by lutooog** [comment]
Hi,
   Yes, your understanding is correct!
   I try to output  via a display, it can be seen that OS is running! But how to config to output to serial port when PSE_FW is enabled?

**Comment by stanleyintel** [comment]
Hi,
The device number of serial port should be changed, so you need to change the "console" settings in your kernel command line. One method is to check the dmesg.

**Comment by lutooog** [comment]
Hi，
  Thank you a lot.
   I can see linux log when I change  hange the "console" to ttyS2.
