### ISSUE TITLE
SBL for Tigerlake

### ISSUE THREAD

**Issue by Renuka018** [slimbootloader/slimbootloader#1815]
Hi,
I built slimbootloader image and stitched it with IFWI for tigerlake board.
However, when I flashed it on the board, nothing is displayed on the screen and the board is turning on and off periodically.
Additionally, can you explain how to disable boot guard on the board?
Thanking in anticipation.

**Comment by stanleyintel** [comment]
Hi Renuka,

You need to get the boot log from the UART port to know what's wrong with the booting. 

About boot guard: it is set during stitch (i.e., the '-b' option for StitchIfwi.py, or the "Boot Guard Profile" if using "fit.exe").

**Comment by Renuka018** [comment]
Hi Stanley,
Thank you for this help.
I will try -b option in the stitching command.
