### ISSUE TITLE
[HEL]Do you have any suggestion what GPIO driver should I use to get access HEL GPIOS?

### ISSUE THREAD

**Issue by lutooog** [slimbootloader/slimbootloader#1866]
Hi,
I want to set GPIO active output low/high form linux code API. Do you have any suggestion what GPIO driver should I use to get access HEL GPIOS?
such as,
void main ()
{
    int value;

     sw_gpio_set_output(gpio_pin, 1);
    ......
    sw_gpio_set_output(gpio_pin, 0);
    ......
    value=sw_gpio_get_input(gpio_pin);
    ......
}

**Comment by stanleyintel** [comment]
Hi,

   Guess "HEL" is typo for EHL.

   Although Linux is out of scope in this forum, you may refer to this discussion https://groups.io/g/slimbootloader/topic/93232860.
