### ISSUE TITLE
Slim Bootloader for Ice Lake-D LCC

### ISSUE THREAD

**Issue by Renuka018** [slimbootloader/slimbootloader#1887]
We are trying to build slimbootloader for Ice Lake-D.
We are facing errors while stitching it on Linux.
Does it support building and stitching it on Linux Ubuntu?

Thanking you in anticipation.

**Comment by Renuka018** [comment]
Yes, installed wine.
Still not able execute Fit Tool.

**Comment by cshur** [comment]
Please discuss here. https://groups.io/g/slimbootloader. Not here.
Your question is too wide. Anyway, first of all, provide and stitch log file to see what error message is.
