### ISSUE TITLE
[EHL]How to config to disable log output when running SBL in linux

### ISSUE THREAD

**Issue by lutooog** [slimbootloader/slimbootloader#1909]
Hi，
    I run SBL to boot linux. I want to disble log output of SBL next reboot， How to config to achieve it？
Thank you！

**Comment by stanleyintel** [comment]
Hi,

   Which log do you want to disable? SBL log or Linux kernel log? And what is the "next reboot" in your question?

    For SBL log, you can (1) build SBL in release mode, i.e.,, add "-r" option in "python BuildLoader.py build ..." AND (2) configure DEBUG_OUTPUT_DEVICE_MASK in your BoardConfig.py to clear BIT1, 2 and 7 (more reference: BootloaderCommonPkg/Include/Guid/LoaderPlatformDataGuid.h)

    For kernel log, you need to configure (or remove) "console=" from kernel command line.
