### ISSUE TITLE
[EHL]How to write or read eeprom ? 

### ISSUE THREAD

**Issue by lutooog** [slimbootloader/slimbootloader#1910]
Hi,
   I want to write or read my eeprom flash(mounted on a i2c bus, chip type:M24C02 ) in SBL? Do you have some API?
Thank you!

**Comment by stanleyintel** [comment]
If the EEPROM is attached to EHL SMBUS controller (B0:D31:F4), you may consider SmBusReadDataByte.

However, if it is mounted on the other i2c bus (B0:D21:F0-3, B0:D25:F0-1, or B0:D16,F0-1), SBL does not have any API for it. You may need to learn how to program the I2C controller by referring to: (1) EHL EDS  (RDC# 614109) and (2) linux driver ([here](https://github.com/torvalds/linux/blob/master/drivers/i2c/busses/i2c-designware-master.c)). e.g., initialize HCNT/LCNT for bus speed, TAR register for slave address, and IC_DATA_CMD, IC_RX_TL, IC_STATUS for read.
