### ISSUE TITLE
LF/CRLF is not coverted to NUL in Multiboot module string

### ISSUE THREAD

**Issue by jiaqingz-intel** [slimbootloader/slimbootloader#1913]
When loading Multiboot container, the LF/CRLF is not coverted to NUL in Multiboot module string when booting

The command I used to build container is below, it was copied from https://github.com/intel/meta-acrn/blob/master/docs/slimbootloader.md

```
sudo python3 GenContainer.py create -cl CMDL:cmdline.txt ACRN:acrn.32.out CMD0:sos-cmdline.txt IMG0:vmlinuz -k ./SblKeys/OS1_TestKey_Priv_RSA3072.pem -a RSA3072_PKCS1_SHA2_384 -t MULTIBOOT -o container.bin
```

Both ACRN and SlimBootloader prints the string of the multiboot module as below, followed by chararcters not belonging to string

```
Linux_bzImage
  LZDMh, 
```

Multiboot Spec (https://www.gnu.org/software/grub/manual/multiboot/multiboot.html#Boot-information-format) says both cmdline and module string are null-terminated string. Is not converting to the NUL termintaor expected?

The cmdline is parsed at

https://github.com/slimbootloader/slimbootloader/blob/a34e54e1754d5dd011786b081760d1d3d286b878/PayloadPkg/OsLoader/OsLoader.c#L444-L467

**Comment by stanleyintel** [comment]
Hi,

  As described in the PR, the patch fixes the issue that a mod string shall be a zero-terminated ASCII string (required by multboot spec), but it does not convert newlines to NULL (not required by multiboot spec).
