### ISSUE TITLE
[ICX-D] Slimbootloader for Idaville LCC

### ISSUE THREAD

**Issue by Renuka018** [slimbootloader/slimbootloader#1977]
Hi,

We are trying Slim Bootloader for Idaville LCC.
We wanted to know whether SBL supports Platform Firmware Resilience (PFR)?

Thanking you in anticipation.

**Comment by cshur** [comment]
PFR is not POR in ICX-D SBL.  If you flash IFWI (BIOS) to support PFR /try to boot and then flash IFWI (SBL), system will hang on POST 00.

**Comment by Renuka018** [comment]
Hi,
So, SBL doesnot support PFR functionality.
And PFR cannot be enabled in SBL for ICX-D

**Comment by randylintw** [comment]
Kindly close it due to a prolonged period of inactivity.
