### ISSUE TITLE
Platform Auth

### ISSUE THREAD

**Issue by dgarske** [slimbootloader/slimbootloader#1982]
Hi Slimboot,

I am reviewing the code for changing the platform auth and not seeing where parameter encryption is being used for the new "random" platform authentication. Perhaps I missed it or not seeing it used later in the call stack. It looks like the `AuthSession` argument to `Tpm2HierarchyChangeAuth` is NULL, which indicates no session is being used and the new auth is sent in the clear?

https://github.com/slimbootloader/slimbootloader/blob/master/BootloaderCommonPkg/Library/TpmLib/TpmLib.c#L949
https://github.com/slimbootloader/slimbootloader/blob/master/BootloaderCommonPkg/Library/TpmLib/TpmLib.c#L898
https://github.com/slimbootloader/slimbootloader/blob/master/BootloaderCommonPkg/Library/TpmLib/Tpm2Hierarchy.c#L62

Thanks,
David Garske, wolfSSL

**Comment by randylintw** [comment]
IKn this CopyAuthSessionCommand it will assign the TPM_RS_PW as session handle 
https://github.com/slimbootloader/slimbootloader/blob/master/BootloaderCommonPkg/Library/TpmLib/Tpm2Help.c#L123
