### ISSUE TITLE
[EHL] RESET botton take long time to do real reset.

### ISSUE THREAD

**Issue by sharkblue2009** [slimbootloader/slimbootloader#2003]
When we push RESET botton on board, the board will NOT reset immediately, but will wait about 10~20 seconds to do the real reset. no matter the system is in BIOS phase or OS phase.

From the EDS vol 1, section 3.10 "reset behavior":

"When a reset is triggered, the PCH will send a warning message to the processor to
allow the processor to attempt to complete any outstanding memory cycles and put
memory into a safe state before the platform is reset. When the processor is ready, it
will send an acknowledge message to the PCH. Once the message is received the PCH
asserts PMC_PLTRST_N."

we measued the signal, from SYS_RESET_N assert to PLTRST_N assert, it take about 10~20 seconds time, does it means, there are no RESET Ack message received? how to debug this?

We are using SBL_MR6 with Intel_CSE_15.40.30.2879

**Comment by stanleyintel** [comment]
Hi Sharkblue,

  I guess your SBL boots with UEFI Payload. Does your UEFI Payload source come from Intel release package or EDK2 open source?

  Also, can you test with the RESET button under OS Loader first?
