### ISSUE TITLE
GetContainerHeaderSize in ContainerLib returns 0

### ISSUE THREAD

**Issue by TagSouth** [slimbootloader/slimbootloader#2053]
Function GetContainerHeaderSize in BootloaderCommonPkg/Library/ContainerLib/ContainerLib.c rejects all containers as invalid, returning a size of 0.

By the time line 82 
`if ((Offset < 0) || (Offset >= ContainerHdr->DataOffset)) {`
is reached on the last iteration, Offset is the distance between (one byte beyond the last component entry) and the start of the container header.  But that is the value stored in ContainerHdr->DataOffset.  So a well-formed container is always rejected.

Replacing that line with
`if ((Offset < 0) || (Offset > ContainerHdr->DataOffset)) {`
makes the function return a non-zero offset.

But it would be a lot simpler to replace the whole function with a
`return ContainerHdr->DataOffset;`

**Comment by bejeanmo** [comment]
Can you attach a container or container header where this is the case? ContainerHdr->DataOffset will be aligned to 4KB (or larger, if a sub container uses a larger alignment), so the actual container header size will typically be less than the data offset. 

There may be an edge case here you pointed out where the last component entry ends at exactly the alignment size which would trigger the issue, in which case changing the **>=**'to **>** is likely the correct solution. However, returning ContainerHdr->DataOffset is typically incorrect.

**Comment by TagSouth** [comment]
[sbl_os.zip](https://github.com/slimbootloader/slimbootloader/files/13219392/sbl_os.zip)
Here is the file I am trying to load.  I know that the operating system inside has issues, as it still doesn't boot even with my change above, but I think its structure as a container file is correct.

**Comment by bejeanmo** [comment]
Yes, it looks like your container structure is more or less sane. Your component alignment is 16-byte and the components have no authentication data. Both of these things are fine, but it means the DataOffset falls immedately after the last component entry in the header. The comparison change to greater than should resolve this issue.
