### ISSUE TITLE
[EHL] sdcard not working at 1.8v signaling mode

### ISSUE THREAD

**Issue by sharkblue2009** [slimbootloader/slimbootloader#2094]
the Sdcard controller is working fine at 3.3V signaling, but after it detected the inserted card is 1.8V compatible, the controller will switch to 1.8v signaling, then the RW access will fail.

If we force the controller working in 3.3v only, the SDcard RW is good. 

If we enable the 1.8v signaling support, and measured the signal, it did switch to 1.8V(SDIO_CLK, SDIO_Dx, SDIO_CMD), but the access then failed.

Thanks a lot!

**Comment by stanleyintel** [comment]
Hello Sharkblue,

   The switch between 1.8V and 3.3V is managed by the OS driver. For instance, you can find a reference driver in the Linux kernel [here](https://github.com/torvalds/linux/blob/24e0d2e527a39f64caeb2e6be39ad5396fb2da5e/drivers/mmc/host/dw_mmc.c#L271). Could you please submit an IPS case to get support from the Intel Yocto (or Windows) team?
