### ISSUE TITLE
UP Squared V2

### ISSUE THREAD

**Issue by gera-k** [slimbootloader/slimbootloader#2166]
Are there plans to add support for the UP Squared V2 board?

**Comment by stanleyintel** [comment]
Hello Gera,

  If you're referring to the [UP Squared V2 board](https://www.aaeon.com/en/p/up-developer-board-intel-elkhart-lake-up-squared-v2) by Aaeon, it would be best to reach out directly to Aaeon to inquire about their plans and support for the board. Additionally, discussing your specific needs with your Intel representative could provide further insight into how Intel might assist you with your project.

**Comment by randylintw** [comment]
Kindly close it due to a prolonged period of inactivity.
