### ISSUE TITLE
Support NHLT table for audio device on APL-UP2

### ISSUE THREAD

**Issue by binbinwu1** [slimbootloader/slimbootloader#218]
NHLT table is not integrated in ACPI table by SBL. NHLT table has audio device specific informatinon, which is needed for audio device to work on APL-UP2.
Could SBL intergrate NHLT table on APL-UP2 to support audio?

**Comment by rprangar** [comment]
Hi

Yes, this is planned in the near future. Meanwhile, you may consider using SBL support for loading NHLT ACPI from IAS. Will provide an update on NHLT support has been added.

Thanks
Ravi

**Comment by rprangar** [comment]
Hi

A PR has been submitted and review is in progress now - https://github.com/slimbootloader/slimbootloader/pull/220

I am planning to close this issue. 

Thanks
Ravi

**Comment by binbinwu1** [comment]
> Hi
> 
> A PR has been submitted and review is in progress now - #220
> 
> I am planning to close this issue.
> 
> Thanks
> Ravi

Thanks
