### ISSUE TITLE
How to boot Windows?

### ISSUE THREAD

**Issue by ziv2013** [slimbootloader/slimbootloader#2266]
Hi,

We have ported SLB to DFRobot LattePanda(Intel N100). It can boot to shell now. But how can we boot to Windows?

There is a Windows in the eMMC and it can boot to Windows with AMI BIOS.

Below is a part of log:

`Created 5 OS boot options (Current: 0)
Stage2: SmmRamBase = 0x4B000000, SmmRamSize = 0x1000000
HECI1 MeFirmwareStatus = 400000 
Stage2: HwState 0x4 TpmType 0x1
Unable to get log area for TCG 2.0 format events !!
Stage2 stack: 0x40000 (stack used 0x870, HOB used 0x1808, 0x3DF88 free)
Stage2 heap: 0x4C0000 (0x270000 used, 0x250000 free, 0x29B448 max used)
Updated SBL Performance Table: S1 = 8030000000ns, S2 = 5265000000ns, OSL = 42000000ns
Payload entry: 0x475A0260
Jump to payload

Payload startup
ACPI PmTimer Base: 0x1808
PCI Express  Base: 0xC0000000

====================Os Loader====================

Press any key within 2 second(s) to enter the command shell
Press any key within 1 second(s) to enter the command shell

Boot options (in HEX):

Idx|ImgType|DevType|DevNum|Flags|HwPart|FsType|SwPart|File/Lbaoffset
  0|      0|   USB |    0 |   0 |   FF | EXT2 |    1 | /boot/sbl_os *Current
  1|      0|  NVME |    1 |   0 |    0 | EXT2 |    1 | /boot/sbl_os
  2|      0|  NVME |    0 |   0 |    0 | EXT2 |    1 | /boot/sbl_os
  3|      0|  SATA |    0 |   0 |   FF | EXT2 |    1 | /boot/sbl_os
  4|      0|   MMC |    0 |   0 |    0 | EXT2 |    1 | /boot/sbl_os

======== Try Booting with Boot Option 0 ========
BootMediumPciBase(0x1400)
Getting boot image from USB
Init USB XHCI - Success
Enumerate Bus - Success
Found 0 USB devices on bus
Failed to init media - Not Found
Failed to Initialize Boot Device - Type 5, Instance 0
Payload normal heap: 0x4000000 (0x4D000 used)
Payload reserved heap: 0x500000 (0x0 used)
Payload stack: 0x20000 (0x534 used)
Deinit USB controller

======== Try Booting with Boot Option 1 ========
BootMediumPciBase(0x0)
Getting boot image from NVME
Init NVMe controller
NVMe initialization failed - Invalid Parameter
Failed to init media - Invalid Parameter
Failed to Initialize Boot Device - Type 6, Instance 1
Payload normal heap: 0x4000000 (0xC000 used)
Payload reserved heap: 0x500000 (0x0 used)
Payload stack: 0x20000 (0x534 used)
Deinit NVMe controller

======== Try Booting with Boot Option 2 ========
BootMediumPciBase(0x0)
Getting boot image from NVME
Init NVMe controller
NVMe initialization failed - Invalid Parameter
Failed to init media - Invalid Parameter
Failed to Initialize Boot Device - Type 6, Instance 0
Payload normal heap: 0x4000000 (0xC000 used)
Payload reserved heap: 0x500000 (0x0 used)
Payload stack: 0x20000 (0x534 used)
Deinit NVMe controller

======== Try Booting with Boot Option 3 ========
BootMediumPciBase(0x1700)
Getting boot image from SATA
Init AHCI controller C00B8000
Not a AHCI controller or Disabled
Failed to init media - Invalid Parameter
Failed to Initialize Boot Device - Type 0, Instance 0
Payload normal heap: 0x4000000 (0xC000 used)
Payload reserved heap: 0x500000 (0x0 used)
Payload stack: 0x20000 (0x534 used)
Deinit AHCI controller 0
Not a AHCI controller or Disabled

======== Try Booting with Boot Option 4 ========
BootMediumPciBase(0x1A00)
Getting boot image from MMC
MMC global data init
Use SDMA instead of ADMA2
MMC Phase 1 init
MMC Phase 2 init
eMMC Tuning feature is disabled!
Try HwPart 0
Try to find boot partition for HW part 0
Protective MBR is not valid format!
Part 00: EFI system partition 0x00000800--0x000327FF, LBA count: 0x32000
Part 01: Microsoft reserved partition 0x00032800--0x0003A7FF, LBA count: 0x8000
Part 02: Basic data partition 0x0003A800--0x072EB7FF, LBA count: 0x72B1000
Part 03: Basic data partition 0x072EB800--0x0747B7FF, LBA count: 0x190000
Partition type: GPT  (4 logical partitions)
Find partition success
BootSlot = 0x0
Init file system failed on SwPart 1, Status = Unsupported
LoadBootImage ImageType-0 Unsupported
Init file system failed, Status = Unsupported
Failed to Load Boot Image
Payload normal heap: 0x4000000 (0xC000 used)
Payload reserved heap: 0x500000 (0x0 used)
Payload stack: 0x20000 (0x534 used)

Shell>`

[boottoshell.log](https://github.com/user-attachments/files/16685378/boottoshell.log)

Thanks,

Ziv

**Comment by stanleyintel** [comment]
Hello Ziv,

  Based on the logs you've provided, it appears that the current payload is set to the OS Loader, which does not support booting Windows. To boot Windows, you will need to switch to using the UEFI Payload.

  For guidance on enabling the UEFI Payload and setting up SBL to boot Windows, you can refer to the following resources: (1) the [how-to](https://slimbootloader.github.io/how-tos/boot-windows.html) doc and (2) SBL Release Notes from Intel (required NDA, and it is RDC# 821209 for your case)

  It is important to note that your board is using the Intel N100, which is categorized as a "**mobile**" SKU of Alder Lake-N (ADL-N). Currently, SBL officially supports only the "### embedded" SKUs. As a result, you may come across some unexpected issues while enabling SBL on a mobile SKU of ADL-N. We will do our best to assist you, but please be aware of these potential limitations.

  Lastly, I recommend visiting the **SBL discussion community** at groups io ([here](https://groups.io/g/slimbootloader/topics)) for additional support. On the Groups IO forum, you can (1) learn from others: Review the topics to see if others have encountered and resolved similar issues, and (2) Ask Questions: If you don't find the answers you're looking for, feel free to ask questions in the group. The community and experts there can provide valuable insights and assistance.
