### ISSUE TITLE
Does Slimbootloader support NVRAM storage?

### ISSUE THREAD

**Issue by jacendi** [slimbootloader/slimbootloader#304]
I'm trying to write (note: since i don’t have a devboard yet, i test it in QEMU) an UEFI driver that writes/reads values in NVRAM storage, but got a problem:
> Variable driver will work at emulated non-volatile variable mode!

Apparently, NVRAM is emulated by UEFI payload in RAM - and it seems to be cleaned after UEFI starts OS bootloader. Is this a QEMU-specific problem or Slimbootloader doesn't support a NVRAM storage on SPI flash/img file?

**Comment by rprangar** [comment]
There are a couple of things involved here.

It looks like you are looking for UEFI variable support. In Slim Bootloader context this is a UEFI payload supported/enabled feature. The open source UEFI payload (EDKII project) supports emulated  UEFI variable by default and is used by virtualized platforms like QEMU. Persistent variable support involves writing the variables to a persistent storage (SPI flash for example) and such storage will have protections enabled on a real platform and will need proper access mechanisms (SMI for example). This can be enabled by UEFI payloads ported to those specific platforms.

Slim Bootloader for its part supports access to SPI flash during boot (example use case - storing memory training parameters), provides a very light weight variable service (not to be confused with UEFI variables) and also recently support was added to read the UEFI variable maintained by the UEFI payload.

Hope this answers your question.
