### ISSUE TITLE
[APL] INT34D2 entry is missing in DSDT

### ISSUE THREAD

**Issue by umaplehurst** [slimbootloader/slimbootloader#390]
A device entry for `INT34D2` is missing under `Platform/ApollolakeBoardPkg/AcpiTables/Dsdt/Platform.asl`. The ACPI entry is necessary for the `intel_pmc_ipc` driver to load up automatically on Linux.

**Comment by myguitar** [comment]
@umaplehurst Thanks for opening this issue. We will check and add the missing device. By the way, what APL board are you using and what Linux are you using for your board?

**Comment by umaplehurst** [comment]
Thanks! This is on a custom board, based on Leaf Hill CRB, kernel v4.14.

**Comment by umaplehurst** [comment]
I've done a little bit more testing:

What works: Linux can successfully use the watchdog, all good.
What doesn't work: sending IPC commands to the PMC doesn't work, the error from the Linux driver is "IPC timed out". I don't get this problem with the official IFWI CRB firmware, v227.51, sending commands to the PMC works fine there.

Please let me know if you'd like me to open this as a fresh bug instead.

**Comment by myguitar** [comment]
> I've done a little bit more testing:
> 
> What works: Linux can successfully use the watchdog, all good.
> What doesn't work: sending IPC commands to the PMC doesn't work, the error from the Linux driver is "IPC timed out". I don't get this problem with the official IFWI CRB firmware, v227.51, sending commands to the PMC works fine there.
> 
> Please let me know if you'd like me to open this as a fresh bug instead.

@umaplehurst Thanks you for more testing. Please open this as a fresh issue and let us know test steps such as Linux sys node command. We will take a look.
