### ISSUE TITLE
ENABLE_EMMC_HS400 needs to also cascade into FSP settings

### ISSUE THREAD

**Issue by umaplehurst** [slimbootloader/slimbootloader#406]
If `BoardConfig.py` has `self.ENABLE_EMMC_HS400 = 0` it looks like this will change SBL behavior, and SBL will not use HS400, but once the OS (or UEFI payload) boots, then the OS will still go into HS400. For the OS to also be limited to HS200, the setting needs to be cascaded into FSP (`FspsConfig->eMMCHostMaxSpeed`).

**Comment by myguitar** [comment]
The fix is under review - https://github.com/slimbootloader/slimbootloader/pull/407. Please let me know if you have any other comment.

**Comment by mauricema** [comment]
Thank you for this info, and it is very helpful.  
I missed it in the original commit.

**Comment by umaplehurst** [comment]
You're very welcome, many thanks for the prompt resolution!
