### ISSUE TITLE
Ubuntu boot failed on WHL platform

### ISSUE THREAD

**Issue by mauricema** [slimbootloader/slimbootloader#606]
Using Ubuntu 18.04,  it does not boot on WHL platform. 

Debug message as below:
Open file 'config.cfg' failed, Status = Not Found
Checking boot/grub/grub.cfg
Load file boot/grub/grub.cfg [size 0x3B9]: Success
Boot Menu:
  0 - * Try Ubuntu without installing
  1 -   Install Ubuntu
  2 -   OEM install (for manufacturers)
  3 -   Check disc for defects
Press '0' ~ '3' to select boot option: 0
Boot from option 0
Load kernel failed !
Failed to Load Boot Image

**Comment by myguitar** [comment]
Resolved by #607
