### ISSUE TITLE
SBL boot hang when USB key board is enabled

### ISSUE THREAD

**Issue by huang-jin-intel** [slimbootloader/slimbootloader#64]
When USB key board is enabled as console input, booting UP2 is halted if a user presses keyboard **before** USB keyboard is initialized. The assert message is the following:

```
====================Os Loader====================

ASSERT [OsLoader] 
.../BootloaderCommonPkg/Library/XhciLib/XhciSched.c(2739): Index != TrsRing->TrbNumber

STAGE_PAYLOAD: System halted!  

```

Pressing keyboard **after** USB keyboard is initialized (typically as soon as logo is shown) works as expect - which enters SBL shell.

**Comment by mauricema** [comment]
We are not able to reproduce this issue yet. 
When we see it this again,  it can be re-opened.
