### ISSUE TITLE
How to use DCI in SBL for debug

### ISSUE THREAD

**Issue by wt-kevin** [slimbootloader/slimbootloader#804]
We have a cable called DCI as below, we will try DCI for debug using this cable on Apollo Lake CRB.
how to build this SBL for DCI debug and how to use it? thank you,
![ITPDCIAMAM2M-2](https://user-images.githubusercontent.com/54980157/89624453-d5306980-d8c8-11ea-81ea-94f6608412a6.jpg)

**Comment by rprangar** [comment]
Hi

Please refer to this video on how to use Intel® System Debugger to enable source level debug using DCI.
https://software.intel.com/content/www/us/en/develop/videos/debugging-edk-ii-based-firmware-image-using-isd.html?wapkw=slim%20bootloader

Thanks
Ravi
