### ISSUE TITLE
[APL] graphics Yocto kernel errors when monitor is not connected

### ISSUE THREAD

**Issue by andreyv1978** [slimbootloader/slimbootloader#822]
Hi

I've got a lot of kernel errors when the DVI monitor is unplugged during Yocto boot. The same can be seen when the monitor unplugged while system is booting. The drivers and i915 works ok (verified), when monitor stay plugged from the beginning and never unplugged.
We actually do not connect monitors to our cards. It needed only for the first setup or integrations.

Ataching the full boot log when the monitor is disconnected from the beginning
[sbl-logging-monitor-disconnected.log](https://github.com/slimbootloader/slimbootloader/files/5108299/sbl-logging-monitor-disconnected.log)

This is when the  monitor is connected
[sbl-logging-monitor-connected.log](https://github.com/slimbootloader/slimbootloader/files/5108268/sbl-logging-monitor-connected.log)

The only difference I can find in SBL is a graphic HOB set for 1440x2560x32 instead of 1920x1080
Graphics Info: 1440 x 2560 x 32 @ 0xA0000000

I am not sure where should I look to fix this. The VBT tables I've created long time ago and only enabled DVI output.

Regards
Andrey

**Comment by mauricema** [comment]
The error is inside the linux kernel, I am not sure if SBL can have control over it.   
VBT is a hardcoded configuration and it needs to match your real hardware connection.  If in VBT, you list a display is available,  but it is not connected, then I believe it is reasonable to see error in kernel.   Maybe you can try to remove VBT table if you know the display is not connected.  It can be done by modifying ENABLE_FRAMEBUFFER_INIT in Platform\ApollolakeBoardPkg\BoardConfig.py.
To disable GFX init,  set as below:
    self.ENABLE_FRAMEBUFFER_INIT  = 0

**Comment by andreyv1978** [comment]
Hi

Looks to me a partial solution self.ENABLE_FRAMEBUFFER_INIT = 0 makes a trick to eliminate GFX kernel problems when no monitor connected, as well as connected. We need something that would provide a monitor, when the setup is required. 
I've looked in  the  SetFrameBufferWriteCombining from Stage2BoardInitLib.c can it be a problem in the allocations of the frame buffer ?

Andrey

**Comment by andreyv1978** [comment]
Looks like enabling KVMR Session makes the drive load as needed with/without monitor
I am still verifying those settings, because made quite a lot of changes in a different places. I will update as soon as confirm about KVMR settings
<img width="918" alt="kvmr-settings" src="https://user-images.githubusercontent.com/9316113/91311739-56359f00-e7ab-11ea-8078-86bcc68662da.PNG">

**Comment by mauricema** [comment]
Thanks for the updates.
BTW, SetFrameBufferWriteCombining() should still work even when framebuffer is not initialized.

**Comment by andreyv1978** [comment]
Are you sure ? from the code it shouldn't 

    if (PcdGetBool (PcdFramebufferInitEnabled)) {
      // Enable framebuffer as WC for performance
      SetFrameBufferWriteCombining ();
    }

**Comment by mauricema** [comment]
Sorry,  I missed the PCD control part.
Yes, that will be skipped.  If skipped, it will have performance impact on framebuffer access.
I think it might be good to always call SetFrameBufferWriteCombining() regardless of PcdFramebufferInitEnabled.

**Comment by andreyv1978** [comment]
do you want me to remove if statesment  from there and test on my board ?
if (PcdGetBool (PcdFramebufferInitEnabled)) {
  // Enable framebuffer as WC for performance
  SetFrameBufferWriteCombining ();
}

and sumbit for review ?
Looks like the VBT settings KVMR made the trick with plugged/unplugged display

**Comment by mauricema** [comment]
Yes,  if you could test it on your board and then submit a PR,  we can merge it in.
Glad to know the KVMR VBT setting resolved your issue.

**Comment by andreyv1978** [comment]
> Thanks for the updates.
> BTW, SetFrameBufferWriteCombining() should still work even when framebuffer is not initialized.

Not sure about this
if self.ENABLE_FRAMEBUFFER_INIT = 0  means display is not working right ? with or without monitor 
Therefore, what the point to call SetFrameBufferWriteCombining  when the framebuffer is actually disabled ?
I've tried to test calling SetFrameBufferWriteCombining (); when self.ENABLE_FRAMEBUFFER_INIT = 0  and see nothing on the monitor plugged back. The kernel without errors

**Comment by mauricema** [comment]
When self.ENABLE_FRAMEBUFFER_INIT = 0 , it just means FSP will not try to do GFX framebuffer enabling, but the framebuffer resource will still be allocated and PCI device is still visible.  So it is still possible that OS might init the GFX later on using its own native driver.  In this case, do not set the WC cache attribute for frame buffer will have negative impact on the performance.   To fully disable GFX,  there is a different CFGDATA called "Igd".

**Comment by andreyv1978** [comment]
good, i see now
will remove 'if' section later next week (on Tuesday) and apply for review

**Comment by andreyv1978** [comment]
Can you please remind me how you run the test of the patch before submitting the pull request ?
