### ISSUE TITLE
Config Editor data in inconsistent format

### ISSUE THREAD

**Issue by JayTalbott** [slimbootloader/slimbootloader#844]
Some of the fields of data shown on the various pages in the Config Editor changed format (hex or decimal) when the configuration data was changed to YAML. As an example, in the Config Editor when changing the settings for CFL-H, on the POWER page the first 4 ratios are in hex, while the next 4 are in decimal. These sort of inconsistencies are all over the place in the configuration data on various pages within the Config Editor. This really should be cleaned up.

**Comment by mauricema** [comment]
Please verify with PR https://github.com/slimbootloader/slimbootloader/pull/846.

**Comment by JayTalbott** [comment]
That appears to have fixed a lot of it, at least for CFL (I didn't check the other platforms). However, for each of the PCIe Clock Config pages, the values are displayed in decimal, but the help text is all hex values. Need to either change the format for these, or change the help text.

**Comment by mauricema** [comment]
Updated the PR to address the additional issues you reported include #850.  Please check.
