### ISSUE TITLE
APL "NOOPT" build fails due to compiler intrinsic functions

### ISSUE THREAD

**Issue by mmustafa88** [slimbootloader/slimbootloader#875]
When build for APL with "NOOPT" flag, the build fails. Please find below errors:

NvmExpressLib.lib(NvmExpressPassthru.obj) : error LNK2001: unresolved external symbol __aullshr
TimeStampLib.lib(TimeStampLib.obj) : error LNK2001: unresolved external symbol __aullshr
IppCryptoLib.lib(pcpbnu32arith.obj) : error LNK2001: unresolved external symbol __aullshr
IppCryptoLib.lib(pcpsm3ca.obj) : error LNK2001: unresolved external symbol __allshl
IppCryptoLib.lib(pcpsha512ca.obj) : error LNK2001: unresolved external symbol __allshl
IppCryptoLib.lib(pcpsha256ca.obj) : error LNK2001: unresolved external symbol __allshl
IppCryptoLib.lib(pcpbnu32arith.obj) : error LNK2001: unresolved external symbol __allshl

**Comment by mauricema** [comment]
Please check PR#876.   Please note, that patch will only address compiling issue caused by compiler intrinsic functions.

**Comment by rprangar** [comment]
Please close the issue if the build issue is resolved.

Thanks.

**Comment by mmustafa88** [comment]
Fixed.
