### ISSUE TITLE
Question: Is there are support for supporting ice lake platform?

### ISSUE THREAD

**Issue by wrongvoid** [slimbootloader/slimbootloader#880]
Hi,

I want know in slim bootloader for ice lake platform. Are there plans to support it?

**Comment by rprangar** [comment]
Hi - Ice lake is not in our plans. We are skipping Ice Lake and will be supporting Tiger Lake soon.

On a general note, since this is not an issue as such, we recommend mailing list for these questions.

**Comment by wrongvoid** [comment]
Is Ice lake –D =>xeon SoC also not supported?
